name: Automatische E-Mail

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Die automatische Ausführung funktioniert!"