name: Automatische E-Mail

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: E-Mail senden
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_ADDRESS }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Du hast schon wieder vergessen, dass du Gott bist ✨"
          to: ${{ secrets.GMAIL_ADDRESS }}
          from: ${{ secrets.GMAIL_ADDRESS }}
          body: |
            Du hast schon wieder vergessen, dass du Gott bist, oder?

            Deine Realität folgt deiner Annahme.

            Du bist die Schöpferin deiner Erfahrung.

            ✨ Alles ist bereits deins. ✨